version: '3'

services:
  # Kong Gateway in DB-less mode
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000" # Kong proxy port
      - "8443:8443" # Kong proxy SSL port
      - "8001:8001" # Kong admin API
      - "8444:8444" # Kong admin API SSL port
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - kong
networks:
  kong: