version: '3'

services:
  # Kong Gateway in DB-less mode
  kong:
    image: kong:latest
    container_name: kong
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
      - ./kong.conf:/etc/kong/kong.conf
    ports:
      - "8000:8000" # Kong proxy port
      - "8443:8443" # Kong proxy SSL port
      - "8001:8001" # Kong admin API
      - "8444:8444" # Kong admin API SSL port
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - kong
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  kong:
    external: true